### PR TITLE
Fibonacci Series

### PR DESCRIPTION
**Pull request by Arika008**
fibonacci series using java

### CODE REVIEW

**Comment by Saikat2407** [comment]
@Arika008 if u find this repo useful , do share and star  the Repo!

**Comment by Arika008** [comment]
@Saikat2407 sure

**Review by Saikat2407 — CHANGES_REQUESTED** [review]
if u could then please work on the issue #50

**Comment by Arika008** [comment]
@Saikat2407  Added #52

**Comment by Akshat-706** [comment]
pls assign it to me

**Pull request closed without merging**
