### PR TITLE
QuickSort in python

### PR DESCRIPTION
**Pull request by deepshikha2708**
image

### CODE REVIEW

**Comment by Saikat2407** [comment]
Good job!!

> image

**Comment by Saikat2407** [comment]
Kindly star the repo!!

**Comment by deepshikha2708** [comment]
I had already starred it

**Comment by deepshikha2708** [comment]
do I need to do anything else?

**Comment by Saikat2407** [comment]
No, you are good to go!

**Comment by deepshikha2708** [comment]
image
why it's showing like this

**Pull request merged**
