### PR TITLE
Added Triangle_Types.cpp

### PR DESCRIPTION
**Pull request by AdityaApte145**
10 types of triangles are printed and switch case logic has been used.

### CODE REVIEW

**Comment by AdityaApte145** [comment]
I have noticed an issue with this code, where it would give an error about **"jump to case label"**, because of variable reinitialization in case 9 and 10 of the code, this issue has been addressed by adding `{}` scope delimiters to every case to prevent this error and indentation has been corrected.

**Comment by Saikat2407** [comment]
Yeah I saw it!!

**Comment by AdityaApte145** [comment]
Hmm... my pull request did not get approved on hacktoberfest. It says **"Excluded"**. Do you know why it happened?

**Comment by Saikat2407** [comment]
solve an issue rather than making changes in existing file, or what you can do is push some algo or important code (leetcode ques).
I hope you got what i wanted to say!!

**Comment by AdityaApte145** [comment]
Yes, Okay. Thanks a lot!

**Pull request merged**
