### PR TITLE
Leetcode Medium Problems

### PR DESCRIPTION
**Pull request by MauryaD**
Solution Leetcode medium problem #238.
Please review and merge.!

Cheers!

### CODE REVIEW

**Review by Saikat2407 — CHANGES_REQUESTED** [review]
Add the problem link on top  of the file in Comments

**Comment by MauryaD** [comment]
Added the Problem Link.

**Review by Saikat2407 — APPROVED** [review]
Approved

**Comment by Saikat2407** [comment]
@MauryaD good job! 👍

**Pull request merged**
