### PR TITLE
Create Heap sort

### PR DESCRIPTION
**Pull request by imdevil69**

### CODE REVIEW

**Comment by imdevil69** [comment]
@Saikat2407 please accept my pr #5

**Comment by Saikat2407** [comment]
Star the Repo first and add the required file under Cpp folder

**Comment by imdevil69** [comment]
Ok .Thankyou for response

**Comment by Saikat2407** [comment]
let me know on completion.

**Comment by imdevil69** [comment]
I am star the Repo and changed folder as well.

**Comment by Saikat2407** [comment]
Good job man!!

**Comment by imdevil69** [comment]
thankyou bro👍

**Pull request merged**
